ecs/tasks/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('ecs.tasks.views',
    url(r'^mine/$', 'my_tasks'),
    url(r'^list/$', 'list'),
    url(r'^backlog/$', 'task_backlog', {'template': 'tasks/backlog.html'}),
    url(r'^task/(?P<task_pk>\d+)/done/$', 'do_task'),
    url(r'^task/(?P<task_pk>\d+)/accept/$', 'accept_task'),
    url(r'^task/(?P<task_pk>\d+)/decline/$', 'decline_task'),
    url(r'^task/(?P<task_pk>\d+)/manage/$', 'manage_task'),
)

ecs/urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin
from django.views.static import serve
from django.views.generic.simple import direct_to_template
from ecs.utils import forceauth
from ecs import workflow
import django

# stuff that needs called at the beginning, but not in settings.py

admin.autodiscover()
workflow.autodiscover()

import logging
from sentry.client.handlers import SentryHandler
logging.getLogger().addHandler(SentryHandler())

# Add StreamHandler to sentry's default so you can catch missed exceptions
logger = logging.getLogger('sentry.errors')
logger.propagate = False
logger.addHandler(logging.StreamHandler())


urlpatterns = patterns('',
    url(r'^$', 'django.views.generic.simple.redirect_to', {'url': '/dashboard/'}),

    url(r'^audit/', include('ecs.audit.urls')),
    url(r'^core/', include('ecs.core.urls')),
    url(r'^dashboard/', include('ecs.dashboard.urls')),
    url(r'^fastlane/', include('ecs.fastlane.urls')),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^feedback/', include('ecs.feedback.urls')),
    url(r'^userswitcher/', include('ecs.userswitcher.urls')),
    url(r'^pdfviewer/', include('ecs.pdfviewer.urls')),
    url(r'^mediaserver/', include('ecs.mediaserver.urls')),
    url(r'^tasks/', include('ecs.tasks.urls')),
    url(r'^communication/', include('ecs.communication.urls')),
    url(r'^billing/', include('ecs.billing.urls')),
    url(r'^help/', include('ecs.help.urls')),
    url(r'^', include('ecs.users.urls')),
    url(r'^', include('ecs.documents.urls')),
    url(r'^', include('ecs.meetings.urls')),
    url(r'^', include('ecs.notifications.urls')),

    url(r'^static/(?P<path>.*)$', forceauth.exempt(serve), {'document_root': settings.MEDIA_ROOT}),
    url(r'^bugshot/', include('ecs.bugshot.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'^test/', direct_to_template, {'template': 'test.html'}),
    #url(r'^tests/killableprocess/$', 'ecs.utils.tests.killableprocess.timeout_view'),
    
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^sentry/', include('sentry.urls')),
)

ecs/tasks/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

class DeclineTaskForm(forms.Form):
    message = forms.CharField(required=False)
    

TASK_MANAGEMENT_CHOICES = [('delegate', _('delegate')),('message', _('message'))]
TASK_QUESTION_TYPE = [('callback', _('callback')), ('somebody', _('somebody')), ('related', _('related') )]

class TaskChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, task):
        return u"%s (%s)" % (task.assigned_to, task)

class ManageTaskForm(forms.Form):
    action = forms.ChoiceField(choices=TASK_MANAGEMENT_CHOICES)
    question_type = forms.ChoiceField(required=False, choices=TASK_QUESTION_TYPE)
    assign_to = forms.ModelChoiceField(queryset=User.objects.all(), required=False, empty_label=_('<group>'))
    question = forms.CharField(required=False, widget=forms.Textarea())
    receiver = forms.ModelChoiceField(queryset=User.objects.all(), required=False)
    
    def __init__(self, *args, **kwargs):
        task = kwargs.pop('task')
        self.task = task
        super(ManageTaskForm, self).__init__(*args, **kwargs)
        self.fields['callback_task'] = TaskChoiceField(queryset=task.trail, required=False)
        self.fields['related_task'] = TaskChoiceField(queryset=task.related_tasks.exclude(assigned_to=None).exclude(pk=task.pk), required=False)
        self.fields['assign_to'].queryset = User.objects.filter(groups__task_types=task.task_type)
        if task.choices:
            self.fields['action'].choices += [('complete_%s' % i, choice[i]) for i, choice in enumerate(task.choices)]
        else:
            self.fields['action'].choices += [('complete', _('complete'))]
        
    def get_choice(self):
        if not hasattr(self, 'choice_index'):
            return None
        return self.task.choices[self.choice_index][0]
        
    def clean_action(self):
        action = self.cleaned_data.get('action')
        if action.startswith('complete'):
            try:
                self.choice_index = int(action.split('_')[1])
                action = 'complete'
            except (ValueError, IndexError):
                pass
        return action
    
    def clean(self):
        cd = self.cleaned_data
        action = cd.get('action')
        if action == 'delegate':
            if 'assign_to' not in cd:
                self._errors['assign_to'] = self.error_class([_(u'You must select a user.')])
        elif action == 'message':
            question_type = cd.get('question_type')
            if question_type == 'callback':
                if not cd.get('callback_task'):
                    self._errors['callback_task'] = self.error_class([_(u'You must select a user.')])
            elif question_type == 'somebody':
                if not cd.get('receiver'):
                    self._errors['receiver'] = self.error_class([_(u'You must select a user.')])
            elif question_type == 'related':
                if not cd.get('related_task'):
                    self._errors['related_task'] = self.error_class([_(u'You must select a user.')])
            elif not question_type:
                self._errors['question_type'] = self.error_class([_(u'You must select a recipient.')])

        return cd

class TaskListFilterForm(forms.Form):
    amg = forms.BooleanField(required=False)
    mpg = forms.BooleanField(required=False)
    thesis = forms.BooleanField(required=False)
    other = forms.BooleanField(required=False)

    mine = forms.BooleanField(required=False)
    assigned = forms.BooleanField(required=False)
    open = forms.BooleanField(required=False)
    proxy = forms.BooleanField(required=False)

    sorting = forms.ChoiceField(required=False, choices=(
        ('deadline', _('Deadline')),
        ('oldest', _('Oldest')),
        ('newest', _('Newest')),
    ))

ecs/tasks/views.py
import random

from django.core.urlresolvers import reverse
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType

from ecs.utils.viewutils import render, redirect_to_next_url
from ecs.users.utils import user_flag_required
from ecs.core.models import Submission
from ecs.communication.models import Thread
from ecs.tasks.models import Task
from ecs.tasks.forms import ManageTaskForm, TaskListFilterForm

@user_flag_required('internal')
def task_backlog(request, submission_pk=None, template='tasks/log.html'):
    tasks = Task.objects.order_by('created_at')
    if submission_pk:
        submission_ct = ContentType.objects.get_for_model(Submission)
        tasks = tasks.filter(content_type=submission_ct, data_id=submission_pk)
    return render(request, template, {
        'tasks': tasks,
    })

def my_tasks(request, template='tasks/compact_list.html'):
    usersettings = request.user.ecs_settings
    submission_ct = ContentType.objects.get_for_model(Submission)

    filter_defaults = {
        'sorting': 'deadline',
    }
    for key in ('amg', 'mpg', 'thesis', 'other', 'mine', 'assigned', 'open', 'proxy'):
        filter_defaults[key] = 'on'

    filterdict = request.POST or usersettings.task_filter or filter_defaults
    filterform = TaskListFilterForm(filterdict)
    filterform.is_valid() # force clean

    usersettings.task_filter = filterform.cleaned_data
    usersettings.save()
    
    all_tasks = Task.objects.for_user(request.user).filter(closed_at=None).select_related('task_type')
    sortings = {
        'deadline': 'workflow_token__deadline',
        'oldest': 'workflow_token__created_at',
        'newest': '-workflow_token__created_at',
    }
    order_by = ['task_type__name', sortings[filterform.cleaned_data['sorting'] or 'deadline'], 'assigned_at']

    all_tasks = Task.objects.for_user(request.user).filter(closed_at=None).select_related('task_type').order_by(*order_by)
    related_url = request.GET.get('url', None)
    if related_url:
        related_tasks = [t for t in all_tasks.filter(assigned_to=request.user, accepted=True) if t.url == related_url]
        if len(related_tasks) == 1:
            return HttpResponseRedirect(reverse('ecs.tasks.views.manage_task', kwargs={'task_pk': related_tasks[0].pk}))
        elif related_tasks:
            pass # XXX: how do we handle this case? (FMD2)

    try:
        submission_pk = int(request.GET['submission'])
    except (KeyError, ValueError):
        submission_pk = None

    if submission_pk:
        submission = get_object_or_404(Submission, pk=submission_pk)
        tasks = all_tasks.filter(content_type=submission_ct, data_id=submission_pk)
    else:
        submission = None
        amg = filterform.cleaned_data['amg']
        mpg = filterform.cleaned_data['mpg']
        thesis = filterform.cleaned_data['thesis']
        other = filterform.cleaned_data['other']
        if amg and mpg and thesis and other:
            tasks = all_tasks
        else:
            tasks = all_tasks.exclude(content_type=submission_ct)
            amg_q = Q(data_id__in=Submission.objects.amg().values('pk').query)
            mpg_q = Q(data_id__in=Submission.objects.mpg().values('pk').query)
            thesis_q = Q(data_id__in=Submission.objects.thesis().values('pk').query)
            submission_tasks = all_tasks.filter(content_type=submission_ct)
            if amg:
                tasks |= submission_tasks.filter(amg_q)
            if mpg:
                tasks |= submission_tasks.filter(mpg_q)
            if thesis:
                tasks |= submission_tasks.filter(thesis_q)
            if other:
                tasks |= submission_tasks.filter(~amg_q & ~mpg_q & ~thesis_q)

    data = {
        'submission': submission,
        'filterform': filterform,
        'form_id': 'task_list_filter_%s' % random.randint(1000000, 9999999),
    }

    task_flavors = {
        'mine': lambda tasks: tasks.filter(assigned_to=request.user, accepted=True),
        'assigned': lambda tasks: tasks.filter(assigned_to=request.user, accepted=False),
        'open': lambda tasks: tasks.filter(assigned_to=None),
        'proxy': lambda tasks: tasks.filter(assigned_to__ecs_profile__indisposed=True),
    }

    for key, func in task_flavors.items():
        context_key = '%s_tasks' % key
        data[context_key] = func(tasks) if filterform.cleaned_data[key] else tasks.none()

    return render(request, template, data)

def list(request):
    return my_tasks(request, template='tasks/list.html')
    
def manage_task(request, task_pk=None):
    task = get_object_or_404(Task, pk=task_pk)
    form = ManageTaskForm(request.POST or None, task=task)
    if request.method == 'POST' and form.is_valid():
        action = form.cleaned_data['action']
        if action == 'complete':
            task.done(user=request.user, choice=form.get_choice())
        
        elif action == 'delegate':
            task.assign(form.cleaned_data['assign_to'])
        
        elif action == 'message':
            question_type = form.cleaned_data['question_type']
            if question_type == 'callback':
                to = form.cleaned_data['callback_task'].assigned_to
            elif question_type == 'somebody':
                to = form.cleaned_data['receiver']
            elif question_type == 'related':
                to = form.cleaned_data['related_task'].assigned_to
            message = Thread.objects.create(
                subject=u'Frage bzgl. %s' % task,
                submission=task.data.get_submission(), 
                task=task,
                text=form.cleaned_data['question'],
                sender=request.user,
                receiver=to,
            )
        return HttpResponseRedirect(reverse('ecs.tasks.views.my_tasks'))
    return render(request, 'tasks/manage_task.html', {
        'form': form,
        'task': task,
    })
    
def accept_task(request, task_pk=None):
    task = get_object_or_404(Task.objects.acceptable_for_user(request.user), pk=task_pk)
    task.accept(request.user)
    return redirect_to_next_url(request, reverse('ecs.tasks.views.my_tasks'))
    
def decline_task(request, task_pk=None):
    task = get_object_or_404(Task.objects.filter(assigned_to=request.user), pk=task_pk)
    task.assign(None)
    return redirect_to_next_url(request, reverse('ecs.tasks.views.my_tasks'))
    
def do_task(request, task_pk=None):
    task = get_object_or_404(Task, pk=task_pk)
    task.done(request.user)
    return redirect_to_next_url(request, reverse('ecs.tasks.views.my_tasks'))

ecs/templates/tasks/backlog.html
{% extends "core.html" %}
{% load core %}

{% block htmlcss %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}tasks/css/tasks.css" />
{% endblock %}

{% block content %}
    {% include 'tasks/log.html' %}
{% endblock %}

ecs/templates/tasks/compact_list.html
{% include "tasks/tasks.inc" %}
{% include "tasks/tasks_js.inc" %}

ecs/templates/tasks/list.html
{% extends "core.html" %}
{% load i18n core %}

{% block menuSelection %}tasks{% endblock %}

{% block headertitle %}{% trans "Tasks" %}{% endblock %}

{% block content %}
    {% include "tasks/tasks.inc" %}
{% endblock %}

{% block jsbottom %}
    {{ block.super }}
    {% include "tasks/tasks_js.inc" %}
{% endblock %}

ecs/templates/tasks/log.html
{% load core %}
<div class="task_back_log">
    <table cellspacing="0">
        <tr>
            <th></th>
            <th>PK</th>
            <th colspan="2">TaskType</th>
            <th colspan="3">Token</th>
            <th>Data</th>
            <th>Accepted</th>
            <th>Locked</th>
            <th>CreatedAt</th>
            <th>CreatedBy</th>
            <th>ClosedAt</th>
            <th>ClosedBy</th>
            <th>AssigendAt</th>
            <th>AssigendTo</th>
        </tr>
        <tr>
            <th></th>
            <th></th>
            <th>Name</th>
            <th>Groups</th>
            <th>Id</th>
            <th>Node</th>
            <th>Workflow</th>
            <th></th><th></th><th></th>
            <th></th><th></th><th></th>
            <th></th><th></th><th></th>
        </tr>
    {% for task in tasks %}
        <tr class="task{% if task.closed_at %} closed{% endif %}">
            <td></td>
            <td>{{ task.pk }}</td>
            <td>{{ task.task_type }}</td>
            <td>{% for group in task.task_type.groups.all %}{{ group }}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
            <td>{{ task.workflow_token.pk }}</td>
            <td>{{ task.workflow_token.node_id }}</td>
            <td>{{ task.workflow_token.workflow_id }}</td>
            <td>{{ task.data|ec_number }}</td>
            <td>{{ task.accepted|yesno }}</td>
            <td>{{ task.locked|yesno }}</td>
            <td>{{ task.created_at|date:'d.m.Y H:i:s' }}</td>
            <td>{{ task.created_by }}</td>
            <td>{{ task.closed_at|date:'d.m.Y H:i:s' }}</td>
            <td>{{ task.closed_by }}</td>
            <td>{{ task.assigned_at|date:'d.m.Y H:i:s' }}</td>
            <td>{{ task.assigned_to }}</td>
        </tr>
    {% endfor %}
    </table>
</div>

ecs/templates/tasks/manage_task.html
{% load core i18n %}

<div id="task_main">
<form action="{% url ecs.tasks.views.manage_task task_pk=task.pk %}" method="post" id="task_form" class="open-in-widget">
    <div class="show_all"><a href="{% url ecs.tasks.views.my_tasks %}" class="open-in-widget">{% trans 'Show all tasks' %}</a></div>
    <h2>{{ task }}</h2>
    {% if task.locked %}
    <span class="lockInfo">Dieser Task kann noch nicht abgeschlossen werden.</span>
    {% endif %}
    {% if form.errors|contains:'action' %}
    <span class="errors">
        Bitte wählen Sie eine Aktion aus.
    </span>
    {% endif %}
    <ul>
        {% if not task.choices %}
        <li>
            <input type="radio" name="action" id="id_action_complete" value="complete"{% ifequal form|form_value:'action' 'complete' %} checked="checked"{% endifequal %} {% if task.locked %} disabled="disabled"{% endif %}/>
            <label for="id_action_complete"><span class="task_complete"></span>{% trans 'Close' %}</label>
        </li>
        {% else %}
            {% for val, label in task.choices %}
            <li>
                <input type="radio" name="action" id="id_action_complete_{{ forloop.counter0 }}" value="complete_{{ forloop.counter0 }}" {% if task.locked %} disabled="disabled"{% endif %}/>
                <label for="id_action_complete_{{ forloop.counter0 }}"><span class="task_reject"></span>{{ label }}</label>
            </li>
            {% endfor %}
        {% endif %}
        <li>
            <input type="radio" name="action" id="id_action_delegate" value="delegate"{% ifequal form|form_value:'action' 'delegate' %} checked="checked"{% endifequal %} />
            <label for="id_action_delegate"><span class="task_delegate"></span>{% trans 'Delegate' %}</label>
            <span class="task_delegate_assign">
                <label for="id_assign_to">An</label>{{ form.assign_to }}
                {% if form.assign_to.errors %}
                    <span class="errors">{{ form.assign_to.errors }}</span>
                {% endif %}
            </span>
        </li>
        <li>
            <input type="radio" name="action" id="id_action_message" value="message"{% ifequal form|form_value:'action' 'message' %} checked="checked"{% endifequal %} />
            <label for="id_action_message"><span class="task_ask"></span>{% trans 'Ask' %}</label>
            {% if form.errors|contains:'question_type' %}
                <span class="errors">{{ form.question_type.errors }}</span>
            {% endif %}
            {% if task.trail %}
              <span class="task_indent">
                  <input type="radio" name="question_type" id="id_question_type_callback" value="callback"{% ifequal form|form_value:'question_type' 'callback' %} checked="checked"{% endifequal %} />
                  <label for="id_question_type_callback">letzte(r) BearbeiterIn</label>
                  {{ form.callback_task }}
                  {% if form.callback_task.errors %}
                      <span class="errors">{{ form.callback_task.errors }}</span>
                  {% endif %}
              </span>
              {% endif %}
              {% if task.related_tasks %}
              <span class="task_indent">
                  <input type="radio" name="question_type" id="id_question_type_related" value="related"{% ifequal form|form_value:'question_type' 'related' %} checked="checked"{% endifequal %} />
                  <label for="id_question_type_related">andere BearbeiterIn</label>
                  {{ form.related_task }}
                  {% if form.related_task.errors %}
                      <span class="errors">{{ form.related_task.errors }}</span>
                  {% endif %}
              </span>
              {% endif %}
              <span class="task_indent">
                  <input type="radio" name="question_type" id="id_question_type_somebody" value="somebody"{% ifequal form|form_value:'question_type' 'somebody' %} checked="checked"{% endifequal %} />
                  <label for="id_question_type_somebody">Person</label>
                  {{ form.receiver }}
                  {% if form.receiver.errors %}
                      <span class="errors">{{ form.receiver.errors }}</span>
                  {% endif %}
              </span>
              <span class="task_indent">
                  {{ form.question }}
                  {% if form.question.errors %}
                      <span class="errors">{{ form.question.errors }}</span>
                  {% endif %}
              </span>
        </li>
        <li>
          <input type="submit" value="Abschicken" />
        </li>
    </ul>
</form>
</div>

<script type="text/javascript">
    window.addEvent('domready', function(){
        var questionTypeInputs = $$('#id_question_type_callback', '#id_question_type_related', '#id_question_type_somebody');
        questionTypeInputs.each(function(radio){
            radio.addEvent('change', function(){
                $('id_action_message').checked = true;
            });
        });
    });
</script>